version: "3"
services:
  rqlite:
    image: rqlite/rqlite
    volumes:
      - ./data:/rqlite/file/data:rw
      - ./users.json:/rqlite/file/users.json
    entrypoint: rqlited -http-addr=localhost:4001 -node-id=1 -auth=/rqlite/file/users.json /rqlite/file/data
    network_mode: host
